git actions

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -15,18 +15,36 @@ jobs:
     steps:
     - uses: actions/checkout@v4
 
-    - name: Get version using custom Gradle task
+    - name: Setup Gradle
+      uses: gradle/actions/setup-gradle@v3
+      with:
+        cache-read-only: false
+
+    - name: Get version from Gradle task
       id: gradle_version
       run: |
-        VERSION=$(./gradlew printVersion -q)
+        # Используем gradle wrapper через gradle command
+        VERSION=$(gradle printVersion -q)
+        
+        # Или альтернативный способ
+        # VERSION=$(./gradlew printVersion --quiet)
         
         if [ -z "$VERSION" ]; then
           echo "Error: Could not get version from Gradle"
           exit 1
         fi
-        
-        echo "Project version: $VERSION"
-        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
+#    - name: Get version using custom Gradle task
+#      id: gradle_version
+#      run: |
+#        VERSION=$(./gradlew printVersion -q)
+#
+#        if [ -z "$VERSION" ]; then
+#          echo "Error: Could not get version from Gradle"
+#          exit 1
+#        fi
+#
+#        echo "Project version: $VERSION"
+#        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
     
     - name: Build the Docker image
       run: |
