git actions

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -20,19 +20,28 @@ jobs:
       with:
         cache-read-only: false
 
+    - name: Make gradlew executable
+      run: chmod +x ./gradlew
+
+    - name: Set up JDK
+      uses: actions/setup-java@v4
+      with:
+        java-version: '17'
+        distribution: 'temurin'
+
     - name: Get version from Gradle task
       id: gradle_version
       run: |
-        # Используем gradle wrapper через gradle command
-        VERSION=$(gradle printVersion -q)
-        
-        # Или альтернативный способ
-        # VERSION=$(./gradlew printVersion --quiet)
-        
-        if [ -z "$VERSION" ]; then
-          echo "Error: Could not get version from Gradle"
-          exit 1
-        fi
+          # printVersion
+          VERSION=$(./gradlew printVersion -q)
+          
+          if [ -z "$VERSION" ]; then
+            echo "Error: Could not get version from Gradle"
+            exit 1
+          fi
+          
+          echo "✅ Project version: $VERSION"
+          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
 #    - name: Get version using custom Gradle task
 #      id: gradle_version
 #      run: |
